# config/config.yaml

server:
  port: "8080"
  mode: "debug" # debug release test

database:
  driver: "mysql"
  dsn: "root:root@tcp(127.0.0.1:3306)/phase4_gin?charset=utf8mb4&parseTime=True&loc=Local"

jwt:
  secret: "nullix"
  expire: 2

log:
  level: "debug" # debug, info, warn, error
  filename: "./logs/app.log"
  max_size: 10
  max_age: 30
  max_backups: 5
